##application.yml
#sever:
#  port:8080
#
##db connection(Mariadb)
#spring:
#  sql:
#    init:
#      platfomr: mariadb
#      encoding : UTF-8
#      mode : always
#
#  datasource:
#    url: jdbc:mariadb://localhost:3306/encore
#    driver-class-name: org.mariadb.jdbc.Driver
#    username : root
#    password : maria
#
#  devtools:
#    liverload :
#      enabled : true
##thymeleaf auto refresh
#  thymeleaf:
#    cache : false
##mariadb mapping
##mapper.xml
#mybatis:
#  type-aliases-package=package : com.example.demo.day2.mapper
#
##mapper.xml location
#  mapper-locations : mybatis/**/*.xml
#
##TestTableMapper.xml 파일이 위치하는 경로 **은 하위폴더 레벨에 상관없이 모든 경로를 뜻하며,
## *는 아무 이름이나 와도 된다는것을 뜻한다.